# Personalize your website info here
title:            Amy Williams
tagline:          'Professional Website for Amy Williams'
description:      'Website and Blog for Amy Williams'
url:              http://awilliams3693.github.io
author:
  name:           'Amy Williams'
  url:            https://twitter.com/freywilly1

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
